### ISSUE TITLE
Create GIT PKGBUILDs

### ISSUE THREAD

**Issue by michael-manley** [michael-manley/Trinity_ArchLinux_PKGBUILD#29]
Convert any R14.0.4 PKGBUILDs to ones that can pull from git repo for people who want the bleeding edge in the R14-git folder

**Comment by Myrddin-Wyllt** [comment]
Here's akode, it compiles, but some rough edges need touch-ups (i.e., pkgver/pkgrel, # Maintainer, group).
<pre>
# Maintainer: 

pkgname=tde-akode-git
pkgver=14.0.5
pkgrel=4
arch=('i686' 'x86_64')
url="http://trinity.pearsoncomputing.net"
license=('GPL2')
groups=('tde-core')
pkgdesc="Akode Sound Library"
depends=('tde-tqt3' 'glu')
makedepends=('pkgconfig' 'cmake')
provides=('akode' 'libakode')
# makeopts=('libtool' '!emptydirs' '!strip')
options=('staticlibs' 'libtool' '!emptydirs' '!strip')

source=("git+https://mirror.git.trinitydesktop.org/gitea/TDE/akode.git")
md5sums=('SKIP')
#install=''
build() {
  cd ${srcdir}/akode
  git submodule update --init --recursive
   msg "Setting PATH, CMAKE and Trinity Environment variables"
   # Source the QT and KDE profile
  [ "$QTDIR" = "" ] && . /usr/share/trinity/srcldr/tqt3.sh
  [ "$TDEDIR" = "" ] && . /usr/share/trinity/srcldr/trinity.sh
   cd $srcdir
   msg "Creating out-of-source build directory: ${srcdir}/build"
   mkdir -p build
   cd build

   msg "Starting cmake..."
   cmake "../akode" \
   -DCMAKE_C_FLAGS:STRING="$CPUOPTIONS" \
   -DCMAKE_CXX_FLAGS:STRING="$CPUOPTIONS $DEBUG_CMAKE_OPT" \
   -DCMAKE_INSTALL_PREFIX=${TDEDIR} \
   -DWITH_GCC_VISIBILITY=ON \
   -DSYSCONF_INSTALL_DIR=${TDEDIR}/etc \
   -DBUILD_ALL=ON
make VERBOSE=1
}

package() {
   msg "Packaging - $pkgname-$pkgver"
   cd ${srcdir}/build
   make -j$(nproc) DESTDIR="${pkgdir}" install

}
</pre>

**Comment by gissf1** [comment]
@Myrddin-Wyllt The standard practice on github is to fork the repository, commit your changes to a branch there, and then submit a pull request.  That would also make it much easier for Michael to merge in your changes, compared to copying the diffs from this bug report.

**Comment by Myrddin-Wyllt** [comment]
@gissf1 Sorry.

**Comment by gissf1** [comment]
@Myrddin-Wyllt  No, there's nothing to be sorry for.  Its just a few clicks on the interface that helps keep the conversations easier to read, and makes the code easier to merge and properly credited.

Just click the "Fork" button on the top right.  Commit your changes in your branch.  Then click the "create pull request" button.  From there, Michael can simply click a button to merge your changes into the code directly without any worries of errors being introduced in the process.  It also makes it easier to see code changes since github shows the changes made vs the original code in a neat format.
