### ISSUE TITLE
Binary packages repo unreachable

### ISSUE THREAD

**Issue by df8oe** [michael-manley/Trinity_ArchLinux_PKGBUILD#47]
Sorry for disturbing you. I cannot find any informations on the web if you have stopped
serving binary Trinity packages from your repo https://repo.nasutek.com/arch/contrib/trinity/x86_64.
Since ~ 1...2 months I only get errors when accessing your repository regardless if I access via
SSL or not. Is there a technical issue or do you no longer support this repo? Additional your email address which is included in your repository public key <mmanley@ntge.net> does no longer exist...

**Comment by gissf1** [comment]
There hasn't been any Github activity on his account since 2020 Jan 25, and there haven't been any updates to this repo since June 2019.  I'm not sure, but I sometimes worry in an online world that people can simply disappear and their projects (and servers) are left to bitrot away into the abyss.

I think it's safe to say that if he is still out there, he has not been responding here.

I will offer some direction though, if you're looking for Arch Trinity packages to try to install it, I haven't yet gotten it to work as a binary or via AUR when the server was still up.  I still hold on to hope that Trinity might gain some more momentum, but it seems to be dying the same way as the original KDE3 did.

Best of luck @df8oe and if you do succeed in getting the AUR packages to build, maybe share your changes via fork or PR and it can help to breathe some life into this project!

**Comment by df8oe** [comment]
I have had got it working here using the binary packages Michael provided. I never have tested if they build on Arch. But because of there are existing binaries I think they *have had built* - otherwise there would not be these binaries ;)

**Comment by michael-manley** [comment]
I unfortunally havent had the time to support it as i did before. I can get the binaries rehosted as that server is still useable just moved. and forgot to restore the repos subdomain.

If anyone wants to give any pull requests ill def take a look at them.

**Comment by df8oe** [comment]
Hi Michael,
many thanks for your feedback. I am happy to hear that it is "only" a lack of time and not the death of the whole project. Unfortunately my free time is also very rare nut I will keep in focus that you are looking for contributors - and I hope others act the same :)

**Comment by df8oe** [comment]
Repository still unreachable...

**Comment by michael-manley** [comment]
I’m in the progress of bringing it back online. I should have it up very soon.

Sent from my iPhone

On Jun 3, 2020, at 11:26 PM, DF8OE <notifications@github.com> wrote:

﻿

Repository still unreachable...

**Comment by michael-manley** [comment]
Ugh, I am trying to find the backup of the repo and am having issues finding that tar.bz2. Bare with me while im trying my hardest to get the repo back online

**Comment by michael-manley** [comment]
Ok finally getting the Arch repos restored back to repo.nasutek.com. They should be uploaded in about an hour

**Comment by df8oe** [comment]
Hi Michael,

thanks for your work. One issue and one "nice-2-have":

issue: file permissions are bad. I can see them but I cannot access them
improvement: provide connection via ssl, too

**Comment by michael-manley** [comment]
Hello,

Try now, It should work fine.

I actually had HTTPS for a while now, just change your url's to https and it will work :)

**Comment by df8oe** [comment]
Hi Michael,

many thanks again for your work. It is running now again - everything is up! This is no longer an issue.
